<a href="https://colab.research.google.com/github/barloff2/python/blob/udemy/Te_damos_la_bienvenida_a_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# Importar Numpy con abrevación 'np'
import numpy as np

In [31]:
# Podemos crear arrays de una dimensión con la función np.array()
array_unidim = np.array([1, 2, 3, 4, 5])

# o un array de dos dimensiones
array_bidim = np.array([[1, 2, 3],
                       [4, 5, 6]])

# o uno de tres dimensiones
array_tridim = np.array([[
                          [1, 2, 3],
                          [4, 5, 6]
                         ],
                         [
                          [7, 8, 9],
                          [10, 11, 12]
                         ]
                        ])

Para cuando uno de estos arrays, podemos obtener sus propiedades, tales como su "Forma", número de dimensiones, tipos de datos y tamaño.

In [32]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño y tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [33]:
# Atributos del array bidimensional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [34]:
# Atributos del array tridimensional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [36]:
# Importamos pandas como pd, y creamos un dataframe a partir del array bidimensional
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos

,0,1,2
0,1,2,3
1,4,5,6


In [37]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
cero = np.zeros((2, 4, 3))
cero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
# Crear array de números en el rango de 0 a 100, con un paso de 5
array_1 = np.arange(0, 100, 5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [43]:
# Creamos un array de números aleatorios enteros comprendidos entre 0 y 10, de tamaño (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[6, 2, 2, 0, 5],
       [9, 1, 3, 6, 0]])

In [53]:
# Crear un array de numeros aleatorios decimales comprendidos entre 0 y 1, te maño 3,5
array_3 = np.random.random((3,5))
array_3

array([[0.09242191, 0.0136295 , 0.83693011, 0.9147879 , 0.70458626],
       [0.3870066 , 0.7056939 , 0.92331116, 0.28815289, 0.68401985],
       [0.5202925 , 0.87736578, 0.92388931, 0.48923016, 0.59621396]])

In [76]:
# Establecemos la "semilla" de números aleatorios en 27

# Creamos un array de números aleatorios enteros compredidos entre 0 y 10, de tamaño (3, 5)
array_4 = np.random.randint(0,10, (3,5))
array_4

array([[1, 2, 0, 3, 3],
       [5, 3, 5, 0, 7],
       [7, 4, 1, 1, 7]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [ ]:
# Encontramos los valoes únicos del array_4
np.unique(array_4)

In [63]:
# Extraemos el elemento de índice 1 del array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [62]:
# Extraemos las primeras dos filas del array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [64]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [65]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))

In [80]:
# Invocamos el array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [69]:
# Invocamos el array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
# Sumamos los dos arrays
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [84]:
# Creamos un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4, 3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
# intentaremos sumar los arrays 6 y 7
# Transposing array_7 to make shapes compatible
array_6 + array_7.T

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta pra que no suceda?

In [86]:
# Entonces creamos otro array de un tamaño (4,3) lleno de unos
array_8 = np.ones((4,3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
# Restamos el array_8 al 7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
# Creamos otros dos arrays de taño 3x3 con números aleatorios del 1 al 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [89]:
# Invocamos el array_9
array_9

array([[1, 4, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [90]:
# invocamos el array_10
array_10

array([[4, 1, 4],
       [1, 2, 4],
       [2, 3, 3]])

In [91]:
# Multiplicamos los últimos dos arrays entre sí
array_9 * array_10

array([[4, 4, 4],
       [1, 2, 8],
       [4, 3, 3]])

In [92]:
# Elevamos el array_9 al cuadrado
np.square(array_9)

array([[ 1, 16,  1],
       [ 1,  1,  4],
       [ 4,  1,  1]])

In [93]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(array_10)

array([[2.        , 1.        , 2.        ],
       [1.        , 1.41421356, 2.        ],
       [1.41421356, 1.73205081, 1.73205081]])

In [94]:
# Hallamos el promedio de los valores del array_9
array_9.mean()

np.float64(1.5555555555555556)

In [95]:
# Hallamos el valor máximo de los valores del array_9
array_9.max()

np.int64(4)

In [96]:
# Hallamos el valor mínimo de los valores del array_9
array_9.min()

np.int64(1)

In [97]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos
array_11 = array_9.reshape((9,1))

In [98]:
# Invocamos el array_11
array_11

array([[1],
       [4],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1]])

In [99]:
# transponemos el array_11
array_11.T

array([[1, 4, 1, 1, 1, 2, 2, 1, 1]])

In [101]:
# comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
array_12 = array_9 > array_10
array_12

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

¿Qué tipos de datos forman parte del array de resultados?

In [102]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [103]:
# Algunos elementos del array_9 es igual a su equivalente del array_10
array_9 == array_10

array([[False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [104]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
array_9 >= array_10

array([[False,  True, False],
       [ True, False, False],
       [ True, False, False]])

In [105]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [106]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(array_9)

array([[1, 1, 4],
       [1, 1, 2],
       [1, 1, 2]])